### ISSUE TITLE
Switch styles

### ISSUE THREAD

**Issue by ecgreb** [mapzen/ios#101]
iOS demo app should include a few of the house styles and allow users to switch between them

**Comment by ecgreb** [comment]
Tangram iOS demo app using remote URL:
https://github.com/tangrams/tangram-es/blob/master/ios/demo/src/MapViewController.m#L155

iOS SDK should use carto CDN (not github) URLs:
https://mapzen.com/documentation/cartography/get-started/

**Comment by ecgreb** [comment]
Also some house stylesheets need to be updated to remove the API key query param from the tile URL and store it in a separate property so it can be properly set by the SDK.

**Comment by nvkelso** [comment]
I'd like to do a new global for this, people should dip into the scene to set these.

**Comment by msmollin** [comment]
@nvkelso Sure. Is that something we need to coordinate with Tangram or is that just a simple variable?

**Comment by ecgreb** [comment]
Mobile apps use the `-more-labels` version of each style when available. Do we need separate PRs to update these?

**Comment by sarahlensing** [comment]
@nvkelso It looks like we still have api keys in the `more-label` variations of the stylesheets on the cdn. Is there a plan to remove them and repush to carto? If not, what is the best way for us to work around this? Should we do as @ecgreb suggests and create branches that remove the keys and then push a second version of this stylesheet to carto?

**Comment by sarahlensing** [comment]
Bundle bubble wrap, cinnabar, refill, walkabout, and zinc via submodules and remove unversioned bubble wrap from project
