### ISSUE TITLE
Tangram framework missing bitcode support in XCode

### ISSUE THREAD

**Issue by ecgreb** [mapzen/ios#102]
Unable to build project locally

**Comment by msmollin** [comment]
ES work here: https://github.com/tangrams/tangram-es/issues/1147

**Comment by karimnaaji** [comment]
@ecgreb it seems that the issue is "unable to *archive* project locally", is that right @msmollin ?

**Comment by ecgreb** [comment]
Tangram pull request need rebase then final review
