### ISSUE TITLE
Assets for Find Me button

### ISSUE THREAD

**Issue by msmollin** [mapzen/ios#104]
We want to use the find me button assets from Eraser Map:
https://github.com/mapzen/eraser-map/blob/master/app/src/main/res/drawable-hdpi/ic_find_me_normal.png

However the buttons are too small on most screens. The recommended minimum size for buttons is 44px for 1x, 88 for 2x, and 132px for 3x, so would it be possible to get those sizes in square layout for the pressed and normal states?

**Comment by souperneon** [comment]
![ic_find_me_normal_1x](https://cloud.githubusercontent.com/assets/6125224/21065423/2487c730-be2e-11e6-938a-21dddf73e6b7.png)
![ic_find_me_normal_2x](https://cloud.githubusercontent.com/assets/6125224/21065427/248ab436-be2e-11e6-8c9c-a66dadbaa9ff.png)
![ic_find_me_normal_3x](https://cloud.githubusercontent.com/assets/6125224/21065422/24858600-be2e-11e6-8a40-43794c685c1b.png)
![ic_find_me_pressed_1x](https://cloud.githubusercontent.com/assets/6125224/21065424/2488d526-be2e-11e6-934c-cbfa99c927ba.png)
![ic_find_me_pressed_2x](https://cloud.githubusercontent.com/assets/6125224/21065426/248a8cd6-be2e-11e6-8386-ece008ea3504.png)
![ic_find_me_pressed_3x](https://cloud.githubusercontent.com/assets/6125224/21065425/248969fa-be2e-11e6-9cc8-72265eb2fbb9.png)

**Comment by souperneon** [comment]
@msmollin lemme know if there is somewhere better I can put them or send you a zip file?
