### ISSUE TITLE
Need a place to run nightly scripts

### ISSUE THREAD

**Issue by msmollin** [mapzen/ios#117]
@heffergm do we have something like a Rundeck server or version of that to have run a simple bash script (https://github.com/mapzen/ios/blob/master/scripts/perform_nightly.sh) so we can have nightly build deploys executed from Circle?

**Comment by msmollin** [comment]
cc @ecgreb

**Comment by heffergm** [comment]
We have no Rundeck/Jenkins/etc. I wrote a lambda function that will do this specific job and can enable it if you desire: https://github.com/mapzen/ios_lambda_deploy

If the request is instead that we host something like Rundeck because you think we're going to be doing a lot of this sort of thing, I'll need to get back to you.

**Comment by msmollin** [comment]
@heffergm oh nice. I would say we probably won't need a dedicated instance yet if Lambda functions will do.

As for Travis, I thought about that route but it felt weird to setup a Travis job to run a CircleCI job - really the solution here would be for Circle to support it. Googling around it seems like the way you went with a Lambda function is the way lots of people seem to be handling it. 

Go ahead and enable it, and let me know if you'd like me to take over the care and feeding of it. Only thing I'm curious about (not being terribly familiar with Lambda) is how it handles injecting the environment variables for the CircleCI Token into the lambda container?

**Comment by heffergm** [comment]
Lambda supports environment variables as part of the configuration. I'll enable it and we can figure out maintenance. It will run at 2am UTC.

**Comment by msmollin** [comment]
Sweet. Thanks sir.
