### ISSUE TITLE
"Installation" and "Getting started" docs

### ISSUE THREAD

**Issue by ecgreb** [mapzen/ios#123]
Minimum docs needed to get the iOS SDK up and running in an app

https://github.com/mapzen/android/blob/master/docs/installation.md

https://github.com/mapzen/android/blob/master/docs/getting-started.md

Publish new docs pages to mapzen.com

**Comment by kkowalsky** [comment]
I'll be watching this and doing some of the maneuvering for the docs release from the product side, assigning this to me

**Comment by msmollin** [comment]
@kkowalsky let me know what kind of format / arrangement you'd like for docs here so they show up properly on the website. I have started writing up the "Getting Started" docs and adding to the existing installation docs.

**Comment by kkowalsky** [comment]
:wave: hi @msmollin, all I need is the main page for the iOS SDK to be named `index.md` and any subsequent pages can have more descriptive names (i.e. data.md, api-reference.md). I can take care of the rest from the docs-generator side
