### ISSUE TITLE
Buildings growing / shrinking at strange points depending on zoom level

### ISSUE THREAD

**Issue by msmollin** [mapzen/ios#129]
So I took a video to explain it better - https://youtu.be/QWBhDOMBVb8

Any thoughts as to what might be causing that? I did a cursory look through the bubble-wrap style sheet I'm bundling in the SDK and didn't see anything odd related to buildings. Maybe this is expected?

**Comment by matteblair** [comment]
This is actually by design 😆 

You could bring this up as a usability issue in the bubble-wrap style, but as far as the rendering engine is concerned this is A.O.K.

**Comment by msmollin** [comment]
@nvkelso thoughts on above?
