### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by msmollin** [mapzen/ios#133]

**Comment by ecgreb** [comment]
We use the Apache 2.0 license across all Android SDKs and all libraries with the exception of Tangram ES which uses MIT.

What is the most popular license for open source iOS projects? Are there any unique implications regarding licensing and how it is related to Apple's terms?

**Comment by msmollin** [comment]
There are some implications, but Apache 2.0 is what we used in Pelias' SDK and that is fine with Apple. This is just a reminder for me to add it.
