### ISSUE TITLE
Make final decision on wrapper vs subclass for Tangram-es integration

### ISSUE THREAD

**Issue by msmollin** [mapzen/ios#143]

**Comment by sarahlensing** [comment]
I'd motion for wrapping `TGMapViewController` with these ideas in mind:

1. It will allow the SDK to provide some convenience for implementing developers that might be out of scope for tangram-es. For example the SDK's `MapViewController` can handle calling `pickFeatureAt` when a developer sets a `mapViewDelegate`. The android SDK does something similar with an internal tap responder [here](https://github.com/mapzen/android/blob/6e52222a8b39c77e5b6cd795b67090668f94c4db/core/src/main/java/com/mapzen/android/graphics/MapzenMap.java#L51-L63)
 
2. It will give the SDK's API a level of protection from underlying tangram-es API changes

What are your thoughts on this?

On a somewhat related note, I'm curious why we don't have a `TGMapView` class that inherits from `GLView`? And then have `TGMapViewController` add this as a subview? It seems like the fundamental UI component for both [MapKit](https://developer.apple.com/reference/mapkit/mkmapview)  and [Google Maps](https://developers.google.com/maps/documentation/ios-sdk/map) inherits from `UIView`, I'm wondering if we want to give developers the same flexibility?

**Comment by msmollin** [comment]
I agree with your thoughts on both points, and am OK proceeding forward if there are no objections from others.

So, the view attached to `TGMapViewController` is a `GLKView` which does, in fact, inherit from `UIView` up the stack - https://developer.apple.com/reference/glkit/glkview#relationships - so the flexibility is maintained.

However, as part of the wrapping work, I would expect the iOS SDK's `MapViewController` class to add the TGMapViewController's GLKView to it's own view hierarchy, and then developers would add MapViewController's view to their own view hierarchy, which would satisfy your concern. 

It would also enable us down the road to enable the `IBInspectable` and `IBDesignable` protocols on the view itself and expose some more interesting functionality in Interface Builder, which isn't really possible in our current subclass setup.

**Comment by ecgreb** [comment]
@karimnaaji @matteblair @tallytalwar any thoughts or concerns on the Tangram side before we move ahead with this change from subclass to wrapper in the SDK?
