### ISSUE TITLE
Update PeliasResponse to use GeoJson decoder

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/ios#178]
Consider these libraries:
https://github.com/mattt/GeoJSONSerialization
https://github.com/raphaelmor/GeoJSON

**Comment by msmollin** [comment]
Per comment here: https://github.com/pelias/pelias-ios-sdk/issues/4#issuecomment-308443453 we can just make a swift struct that matches the GeoJSON schema and use the new Swift 4 JSON decoder to accomplish this.
