### ISSUE TITLE
Allow setting selector on annotations added to the map

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/ios#180]
`MapViewController` currently handles translating `PeliasMapkitAnnotation`s into TG markers. If developers want to do something when these underlying markers are selected, they have to implement `MapMarkerSelectDelegate`'s `func mapController(_ controller: MapViewController, didSelectMarker markerPickResult: TGMarkerPickResult, atScreenPosition position: CGPoint)` and use the `markerIdToAnnotation` maps to get back the original annotation object. Instead we could treat these annotations more like buttons and allow a selector to be set on `PeliasMapkitAnnotation` so the flow of adding an annotation would look like this:

```
let annotation = PeliasMapkitAnnotation(coordinate: coordinate, title: name, subtitle: nil, data: addressDictionary as [String : AnyObject]?)
annotation.selector = #selector(SearchPinsViewController.onAnnotationSelected(annotation:))
mapController.add(annotation)

func onAnnotationSelected(annotation: PeliasMapkitAnnotation) {
    //show alert
}
```

Instead of this:
```
let annotation = PeliasMapkitAnnotation(coordinate: coordinate, title: name, subtitle: nil, data: addressDictionary as [String : AnyObject]?)
mapController.add(annotation)

func mapController(_ controller: MapViewController, didSelectMarker markerPickResult: TGMarkerPickResult, atScreenPosition position: CGPoint) {
    let markerId = markerPickResult.identifier
    let annotation = markerIdToAnnotation[markerId]
    //show alert
}
```

If we did this we might want to consider filter out calling `MapMarkerSelectDelegate` for marker ids associated with `PeliasMapkitAnnotation`.

**Comment by ecgreb** [comment]
Related Tangram ES work https://github.com/tangrams/tangram-es/pull/1315
