### ISSUE TITLE
Circle CI nightly builds no longer display a map

### ISSUE THREAD

**Issue by ecgreb** [mapzen/ios#195]
The combination of removing the hard-coded Mapzen API key from the demo app (good) and turning off keyless access to vector tiles (good) means that nightly builds on Circle CI now fail to load a map (bad).

We need to come up with a way to securely inject a demo API key into the iOS sample app at build time on Circle CI. Perhaps some combination of a Circle CI environment variable and build properties.

**Comment by msmollin** [comment]
This will require some updates to the project and circle CI to get the iOS app to pick up at build time. I found this blog referencing how to pass user variables at compile time to via `xcodebuild` however the article is from 2013 so things might've changed:
http://blog.manbolo.com/2013/05/17/passing-user-variable-to-xcodebuild
