### ISSUE TITLE
Migrate TGMapMarkerId to TGMarker

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/ios#207]
When new version of Tangram is released use the new TGMarker class

Tangram PR: https://github.com/tangrams/tangram-es/pull/1315

**Comment by karimnaaji** [comment]
Just pushed a preview of 0.5.1 for testing prior for this work https://github.com/tangrams/ios-framework/tree/preview-0.5.1.

**Comment by sarahlensing** [comment]
The work for this can be broken into stages:

Stage 1:
- Do straight forward migration from `TGMapMarkerId` to `TGMarker`
    - Update properties in `MapViewController`
- Remove marker methods from `MapViewController`
- Update sample app

Stage 2:
- Create SDK `Marker` class to wrap `TGMarker`
- Add convenience methods like `isVisible`, `setSize`, `setBackgroundColor`, `setInteractive` (having it default to true) and then handle concatenating values to internal style string
- Provide system marker types
    - Like `UIBarButtonItem`'s `- (instancetype)initWithBarButtonSystemItem:(UIBarButtonSystemItem)systemItem target:(nullable id)target action:(nullable SEL)action;` we can provide an easy way for developers to add markers with sdk styles such as `sdk-point-overlay`

Stage 3:
- Consider removing `MapMarkerSelectDelegate` and replace with target/action like we did with `PeliasMapkitAnnotation`
- Update `PeliasMapkitAnnotation` to inherit from `Marker` class and encapsulate styling information

@msmollin What are your thoughts on breaking this up into these 3 chunks of work? I'm thinking that we do the first two stages for launch and then mark stage three as a nice to have.

**Comment by msmollin** [comment]
Stage 1 and 2 sound fine. We should list out specifically what convenience methods we want (I think those 4 you listed are good to start with). I have thoughts on how to approach this after doing string manipulation with Pelias and how to avoid doing it :) 

Stage 3 I'd rather see us just deprecate `PeliasMapkitAnnotation` all-together and rethink how we approach that system.

Lets make tickets for stage 1 and 2 and then we can discuss 3 more in depth.

**Comment by sarahlensing** [comment]
:)

I'll keep this ticket as the representation for stage 1. Created this for stage 2: https://github.com/mapzen/ios/issues/221
