### ISSUE TITLE
Make sample app's search example more obvious

### ISSUE THREAD

**Issue by msmollin** [mapzen/ios#214]
### Description

Currently in the Sample app it's non-obvious to users that the "Search" tab requires hitting enter to perform a search to display pins on the map. Couple options I see:

- Enhance/change the UI to direct users better
- Just use Autocomplete for both search and routing

@sarahlensing / @ecgreb / @souperneon thoughts on this?

**Comment by souperneon** [comment]
@msmollin Chuck showed me some sketches for redesigning the structure of the demo app on iOS. Those should address this ticket?

**Comment by ecgreb** [comment]
Yes I believe so! App cleanup work is detailed here.

**Comment by msmollin** [comment]
Closing because work will done as part of #224
