### ISSUE TITLE
Create SDK Marker Class

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/ios#221]
### Description
Create SDK Marker class to wrap TGMarker

- Add convenience methods: `isVisible`, `setSize`, `setBackgroundColor`, `setInteractive` (having it default to true) and then handle concatenating values to internal style string
- Provide system marker types
    - Like UIBarButtonItem's - (instancetype)initWithBarButtonSystemItem:(UIBarButtonSystemItem)systemItem target:(nullable id)target action:(nullable SEL)action; we can provide an easy way for developers to add markers with sdk styles such as sdk-point-overlay

**Comment by msmollin** [comment]
We'll want to try to integrate https://github.com/tangrams/tangram-es/issues/1391 fixes (whatever they turn out to be) so we can properly throw errors again.

**Comment by sarahlensing** [comment]
Related to the above tangram issue: https://github.com/tangrams/tangram-es/issues/1370
