### ISSUE TITLE
Add copy files target from xcode project configuration

### ISSUE THREAD

**Issue by karimnaaji** [mapzen/ios#225]
Right now some of the styles in the style switcher are missing resources. For fonts, it wouldn't be visible since we provide proper fallback when a font is missing in tangram-es, but some other resources would make the style not rendering a complete layers (walkabout style is missing the terrain layer since the spheremaps are not added). 

A simple fix to test this is to add all of the images within `scenes/styles/walkabout/images/` within a _copy files_ target in the xcode build phases to see the terrain layer appear. Maybe we could configure cocoapods so updating styles wouldn't require updating the project with new style resources that might appear.

Once styles are within the framework bundle, this wouldn't be an issue anymore.

**Comment by matteblair** [comment]
Would this be easier to manage if we used the zip-bundle form of scenes?

**Comment by karimnaaji** [comment]
It would definitely reduce the number of dependencies to add to the build phases in xcode (only the zip files of each style vs all dependencies of each of style), so if there is no cocoapods alternative it would probably make configuration simpler.

**Comment by tallytalwar** [comment]
zip bundle manager for scene is almost there. Need some more work to handle network resources.

**Comment by msmollin** [comment]
@matteblair unlikely - part of the issue is how dynamic frameworks present themselves to the including application (which in and of itself is basically treated as a framework to other frameworks). The cocoapods guys have an explanation here: http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/#dynamic-frameworks-vs.-static-libraries

**Comment by tallytalwar** [comment]
> which in and of itself is basically treated as a framework to other frameworks

Thats confusing

**Comment by msmollin** [comment]
Heh slightly at first, yes. It however clears up a logical fork in how you access resources. With static libraries, it goes something like "If it was inside a static lib, you get imported into the app bundle, whereas in a framework, you do it this other way." Now that people don't have to hack around building frameworks for iOS, it's just the latter way. That's preferable in my opinion, but it does have the downside of making things slightly more complicated.
