### ISSUE TITLE
Computed properties for tilt/float/etc. that pass values into TGViewController are broken

### ISSUE THREAD

**Issue by msmollin** [mapzen/ios#235]
Current code:
```  
open var rotation: Float {
    set {
      tgViewController.rotation = rotation
    }
    get {
      return tgViewController.rotation
    }
  }
```

`= rotation` on this side is actually pulling from the TGViewController's current `rotation` value, so its effectively always zero and ignores the value.

It really should be:

```tgViewController.rotation = newValue```

**Comment by ecgreb** [comment]
So similar... why can't we just use the same language?

```kotlin
open var rotation: Float
    set(value) {
        tgViewController.rotation = value
    }
    get() = tgViewController.rotation
```

https://kotlinlang.org/docs/reference/properties.html#getters-and-setters

**Comment by msmollin** [comment]
https://github.com/apple/swift/blob/master/docs/Android.md

:)

**Comment by ecgreb** [comment]
I'm in
