### ISSUE TITLE
Update attribution

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/ios#257]
As per https://mapzen.com/rights/ and http://www.openstreetmap.org/copyright:
“© Mapzen, OpenStreetMap, and others”

**Comment by msmollin** [comment]
Updated in the sample app cleanup. Just an FYI for @mjcunningham & @souperneon I had to drop the attribution font size from 14 -> 11 to get it to fit on small screen devices.

<img width="432" alt="screen shot 2017-04-07 at 9 35 31 am" src="https://cloud.githubusercontent.com/assets/1163880/24802334/9437c2a2-1b75-11e7-915b-e3bdae849664.png">

**Comment by msmollin** [comment]
Per resulting discussion with @mjcunningham & @randymeech we're going to hold off on using this markup and instead update our "Rights" page to have a specific section for mobile.

cc @ecgreb / @sarahlensing
