### ISSUE TITLE
Write iOS launch blog post

### ISSUE THREAD

**Issue by ecgreb** [mapzen/ios#263]
- [x] SDK (https://github.com/mapzen/website/pull/1556/)
  - [precog  link](https://precog.mapzen.com/mapzen/website/ios-sdk-1.0.0/blog/ios-sdk-1.0.0)
- [x] Maps (https://github.com/mapzen/website/pull/1591)
  - [precog link](https://precog.mapzen.com/mapzen/website/karimnaaji/blog/making-maps-on-ios-with-tangram/blog/)
- [x] Search (https://github.com/mapzen/website/pull/1554) 
  - [precog link](https://precog.mapzen.com/mapzen/website/mapzen-search-1.0.0/blog/)
- [x] Routing (https://github.com/mapzen/website/pull/1599)
  - [precog link](https://precog.mapzen.com/mapzen/website/matts/ios-turnbyturn-launch/blog/)

**Comment by msmollin** [comment]
Depends upon screen recording getting GIF-ized from #295
