### ISSUE TITLE
iOS demo app launcher icon

### ISSUE THREAD

**Issue by ecgreb** [mapzen/ios#264]

**Comment by msmollin** [comment]
App icon specifics:
https://developer.apple.com/ios/human-interface-guidelines/graphics/app-icon/

There are 5 sizes for the launcher icon:
<img width="545" alt="screen shot 2017-04-12 at 4 38 10 pm" src="https://cloud.githubusercontent.com/assets/1163880/24978377/74a8d854-1f9e-11e7-8d40-0fbfcfc08048.png">

Ignore the numbers in parentheses. They're what apple will convert them to on the particular device.

Then if we want to be 100% complete we also need the accessory icons:

<img width="301" alt="screen shot 2017-04-12 at 4 39 33 pm" src="https://cloud.githubusercontent.com/assets/1163880/24978420/a3b8a804-1f9e-11e7-9650-98f0febf1238.png">

which is another 7 sizes.

**Comment by msmollin** [comment]
Since we're not going to the app store with this we can probably leave it out.

**Comment by msmollin** [comment]
We don't need the accessory icons either really :)

**Comment by souperneon** [comment]
[Assets for iOS.zip](https://github.com/mapzen/ios/files/920069/Assets.for.iOS.zip)

I have fulfilled all your wishes!
