### ISSUE TITLE
[discuss] Add crash reporting

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/ios#276]
We should add crash reporting into the sample app. 

Using HockeyApp seems like a good first place to start since we are already using it for distribution: https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/hockeyapp-for-ios#crashreporting. With hockeyapp we can allow auto-sending of reports or user confirmation.

**Comment by msmollin** [comment]
Thought about this a bit. Given what we did to inject the Mapzen API keys I think we can probably satisfy this while not causing people too much grief who want to `pod try Mapzen-ios-sdk`.
