### ISSUE TITLE
Generate xcode project using cmake and build on Travis

### ISSUE THREAD

**Issue by msmollin** [mapzen/ios#30]

**Comment by ecgreb** [comment]
Depends on build process updates in #32

**Comment by blair1618** [comment]
The corresponding work in tangram-es is here: https://github.com/tangrams/tangram-es/issues/917

**Comment by ecgreb** [comment]
shell script to push binary framework to its own repo?

**Comment by ecgreb** [comment]
https://github.com/tangrams/tangram-es/pull/1003

**Comment by tallytalwar** [comment]
https://github.com/tangrams/tangram-es/pull/1003 got merged to tangram-es master!
