### ISSUE TITLE
Tangram-es bundle version string missing - think about how to resolve

### ISSUE THREAD

**Issue by msmollin** [mapzen/ios#320]

**Comment by msmollin** [comment]
https://github.com/tangrams/tangram-es/issues/1506

**Comment by matteblair** [comment]
Any problem with just injecting the Circle CI build number as `CFBundleVersion`? This presupposes, of course, that we do our release builds on Circle instead of locally :)

**Comment by msmollin** [comment]
For the Tangram-es builds, yep that would work (going along with the presupposition).

However for the Mapzen iOS SDK that's not an option because our cocoapod is a source code pod, so we don't have a build number to inject.

**Comment by darkwizzard** [comment]
Hello, 

There is any update of this?

Thanks you.

**Comment by msmollin** [comment]
This has been resolved in the upstream dependency. We're prepping a release for this repository and it will resolve this as well. Keep an eye out here over the next few days.

**Comment by msmollin** [comment]
@darkwizzard 1.1.0 has been released which fixes this. https://github.com/mapzen/ios/releases/tag/v1.1.0

**Comment by darkwizzard** [comment]
Thanks you very much.
