### ISSUE TITLE
Test Tangram-es 0.8

### ISSUE THREAD

**Issue by msmollin** [mapzen/ios#351]

**Comment by darkwizzard** [comment]
When it be in cocoapods? Thanks.

**Comment by msmollin** [comment]
@darkwizzard are you referring to Tangram-es 0.8 or the Mapzen iOS SDK that incorporates it?

Tangram-es 0.8 is already in cocoapods.

The Mapzen iOS SDK release is imminent. We're working through some additional testing steps internally and should be ready to launch with the next few days.

**Comment by darkwizzard** [comment]
Mapzen iOS SDK that incorporates it. Thanks for your reply.
