### ISSUE TITLE
Mapzen SDK - Add a map to your storyboard

### ISSUE THREAD

**Issue by nolispe280** [mapzen/ios#363]
### Description
Hi everyone, I have tried to use the Mapzen ios SDK but can't even add a map to my storyboard. I'm stuck at changing the subclass of the UIViewController to MZMapViewController. Basically when I do it I get a message saying "Not Applicable". 

![picture1](https://user-images.githubusercontent.com/32175056/30710379-aaf43138-9f05-11e7-877b-ac3b7a281d5a.png)

Does anyone know a simple way to add a map to my storyboard?

**Comment by msmollin** [comment]
Just follow these instructions here: https://vimeo.com/235418187
