### ISSUE TITLE
Two current location icons on map

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/ios#370]
### Description
Two current location markers are displayed on map when only one is expected

### Steps to Reproduce
Load a stylesheet twice

```swift
let bubblewrap = BubbleWrapStyle()
try? loadStyleSheetAsync(bubblewrap) { (style) in
  self.styleLoaded = true
  let _ = self.showCurrentLocation(true)
  self.showFindMeButon(true)
  try? self.loadStyleSheet(bubblewrap)
}
```

![img_1034](https://user-images.githubusercontent.com/494323/31625426-49914cca-b263-11e7-96fd-6173d9bc8f96.PNG)

### Mapzen SDK & iOS Version
Mapzen SDK 1.1.0-rc1
iOS 10.3.3

**Comment by tallytalwar** [comment]
Thats a feature! :D Time travel!
