### ISSUE TITLE
Scene file resources must maintain relative path to scene file in bundle

### ISSUE THREAD

**Issue by blair1618** [mapzen/ios#38]
e.g. if a scene file resides at `my-scene/scene.yaml` and uses icons from `my-scene/images/icons.png` then the relative path from `scene.yaml` to the icons file in the bundle must be `images/icons.png`.

**Comment by msmollin** [comment]
Fixed in https://github.com/mapzen/ios/commit/edc17c4fa7f460c53d3bddc550db91baae72e176

Since it was just a project file update I'll run a build and we can confirm working there @mjcunningham  - trying to review xcode project file updates in a PR is a pain.
