### ISSUE TITLE
Expose vector tiles key API for tangram to use

### ISSUE THREAD

**Issue by msmollin** [mapzen/ios#45]

**Comment by msmollin** [comment]
https://github.com/tangrams/tangram-es/issues/853

**Comment by ecgreb** [comment]
Use apply scene update capabilities to modify stylesheet exposed in #54

**Comment by msmollin** [comment]
Closing this since #54 took care of this and will be merged in by #81

**Comment by karimnaaji** [comment]
I think that this task should still remain, since the SDK layer can make developer life easier by wrapping this particular scene update in a simpler method to use for a specific house style.

**Comment by msmollin** [comment]
Agreed, and that's what I was planning on doing https://github.com/mapzen/ios/issues/67 for the in-house styles. This was specifically for exposing that functionality in Tangram.
