### ISSUE TITLE
Analyze size and performance

### ISSUE THREAD

**Issue by ecgreb** [mapzen/ios#61]
It would be good to have the following metrics available for the Mapzen SDK:
- Framework size
- Impact on client app size (is this the same?)
- Comprehensive list of dependencies including transitive dependencies (can we omit any currently in use?)
- Comprehensive list of permissions (and those that can/should be optionally added by client apps)
- Basic performance metrics for startup time, map load time, cached vs. non-cached tiles, etc.
- What else?

**Comment by tallytalwar** [comment]
Does it make sense to have a comparison with other maping SDKs? Maybe something for the blog posts?

**Comment by sarahlensing** [comment]
Consider adding a linter: https://github.com/realm/SwiftLint
