### ISSUE TITLE
Document main framework and dependencies.

### ISSUE THREAD

**Issue by msmollin** [mapzen/ios#63]
- [x] Tangram https://github.com/tangrams/tangram-es/pull/1290
- [ ] Pelias
- [x] On the Road
- [ ] SDK

**Comment by ecgreb** [comment]
https://github.com/tangrams/tangram-es/pull/1290

**Comment by ecgreb** [comment]
Talk with @rmglennon and @meetar about how code docs get deployed to the website.

**Comment by ecgreb** [comment]
Breaking out deployment into its own issue that I assigned to me. Will work on this for iOS and Android in conjunction. Not a blocker for beta.

https://github.com/mapzen/ios/issues/189
https://github.com/mapzen/android/issues/300

**Comment by msmollin** [comment]
#192 for Pelias to go separately.
