### ISSUE TITLE
Background Location Update Support

### ISSUE THREAD

**Issue by msmollin** [mapzen/ios#92]
Need to figure out where we draw the line with our internal handling of backgrounding and where the implementing developer needs to be involved.

**Comment by darkwizzard** [comment]
Hello,

Is there any update on this topic? Or a date of development?

Regards,
Thanks you.

**Comment by msmollin** [comment]
Thanks for reaching out!

We're targeting late Q3/ early Q4 for completion on this front. There are changes inbound from iOS 11 related to how background location security works, so we're having to reconsider some of the design choices we made originally in the location management layer and see how that affects our roadmap for this and turn-by-turn. 

Will definetly keep this up to date as we progress on that front.

**Comment by nolispe280** [comment]
Hi,
I think I posted a new issue yesterday on this exact topic. Any update on the issue?
Cheers!

**Comment by msmollin** [comment]
Indeed! I'm currently finishing up additional testing around it as part of this work https://github.com/mapzen/ios/pull/385

I will make sure this issue gets updated as well to denote when it merges in.
